#import "MainWindowController.h"
#import "CodexConfigWriter.h"
#import "CodexModelCatalogWriter.h"
#import "ProviderConnectionTester.h"

@interface MainWindowController () {
    ProviderStore *_store;
    LocalGateway *_gateway;
    UsageStore *_usageStore;
    NSStackView *_listStack;
    NSTextField *_messageLabel;
    NSTextField *_nameField;
    NSSecureTextField *_apiKeyField;
    NSTextField *_baseURLField;
    NSStackView *_modelRowsStack;
    NSTextField *_tagField;
    NSView *_apiFormatControl;
    NSButton *_testButton;
    NSButton *_saveButton;
    NSMutableArray<NSMutableDictionary *> *_modelRows;
    NSString *_editingId;
    NSView *_contentHost;
    NSView *_sidebarView;
    NSView *_sidebarFooterView;
    NSTextField *_sidebarBrandTitleLabel;
    NSTextField *_sidebarBrandSubtitleLabel;
    NSTextField *_sidebarFooterTitleLabel;
    NSButton *_navMainButton;
    NSButton *_navSettingsButton;
    NSTextField *_sidebarCurrentLabel;
    NSTextField *_sidebarProxyLabel;
    NSString *_page;
    NSString *_settingsTab;
    NSString *_pendingLanguage;
    NSString *_selectedAPIFormat;
    NSTextField *_codexDirField;
    NSSwitch *_launchAtLoginSwitch;
    NSSwitch *_showRouteControlsSwitch;
    NSSwitch *_routeEnabledSwitch;
    NSSwitch *_failoverSwitch;
    NSTextField *_listenAddressField;
    NSTextField *_listenPortField;
    NSButton *_routePortCheckButton;
    NSTextField *_routePortStatusLabel;
    NSTextField *_statsProviderJumpField;
    NSTextField *_statsModelJumpField;
    NSTextField *_statsLogJumpField;
    NSString *_checkedFingerprint;
    NSString *_activeTestFingerprint;
    NSString *_routePortCheckFingerprint;
    NSInteger _statsProviderPage;
    NSInteger _statsModelPage;
    NSInteger _statsLogPage;
    BOOL _connectionCheckPassed;
    BOOL _isTestingConnection;
    BOOL _routePortCheckPassed;
}
@end

@interface MainWindowController (Internal)
- (instancetype)initWithStore:(ProviderStore *)store gateway:(LocalGateway *)gateway usageStore:(UsageStore *)usageStore;
- (void)usageStoreDidChange:(NSNotification *)notification;
- (void)buildUI;
- (NSColor *)colorWithHex:(NSUInteger)hex;
- (BOOL)isDarkAppearance;
- (NSColor *)appBackgroundColor;
- (NSColor *)sidebarBackgroundColor;
- (NSColor *)panelBackgroundColor;
- (NSColor *)softPanelBackgroundColor;
- (NSColor *)lineColor;
- (NSColor *)primaryBlueColor;
- (NSColor *)primaryTintColor;
- (NSColor *)mutedTextColor;
- (NSColor *)quietTextColor;
- (NSView *)coloredView:(NSColor *)background border:(BOOL)border;
- (NSView *)centeredTextContainerWithText:(NSString *)text textColor:(NSColor *)textColor backgroundColor:(NSColor *)backgroundColor font:(NSFont *)font cornerRadius:(CGFloat)cornerRadius minWidth:(CGFloat)minWidth height:(CGFloat)height horizontalPadding:(CGFloat)horizontalPadding;
- (NSView *)centeredTextContainerWithText:(NSString *)text textColor:(NSColor *)textColor backgroundColor:(NSColor *)backgroundColor font:(NSFont *)font cornerRadius:(CGFloat)cornerRadius minWidth:(CGFloat)minWidth height:(CGFloat)height horizontalPadding:(CGFloat)horizontalPadding label:(NSTextField **)labelOut;
- (NSButton *)styledButton:(NSString *)title action:(SEL)action primary:(BOOL)primary;
- (NSButton *)navButton:(NSString *)title action:(SEL)action active:(BOOL)active;
- (void)updateNavButton:(NSButton *)button title:(NSString *)title active:(BOOL)active;
- (void)styleExistingButton:(NSButton *)button primary:(BOOL)primary;
- (NSView *)sidebarView;
- (void)refreshSidebar;
- (void)refreshThemeColors;
- (void)clearContentHost;
- (void)renderCurrentPage;
- (NSStackView *)pageRootWithSpacing:(CGFloat)spacing;
- (NSButton *)iconButton:(NSString *)title action:(SEL)action;
- (NSStackView *)pageHeaderWithTitle:(NSString *)title subtitle:(NSString *)subtitle back:(BOOL)back;
- (void)renderMainPage;
- (void)renderFormPageWithTitle:(NSString *)titleText;
- (void)renderSettingsPage;
- (NSView *)settingsTabs;
- (NSView *)generalSettingsView;
- (NSView *)routeSettingsView;
- (NSView *)statsSettingsView;
- (NSView *)diagnosticsSettingsView;
- (NSView *)aboutSettingsView;
- (NSView *)sectionTitle:(NSString *)title subtitle:(NSString *)subtitle;
- (NSView *)statCard:(NSString *)title value:(NSString *)value;
- (NSView *)trendLegendItemWithTitle:(NSString *)title value:(NSString *)value color:(NSColor *)color;
- (NSView *)trendLegendViewWithInput:(NSString *)input output:(NSString *)output cached:(NSString *)cached;
- (NSView *)tableLikeViewWithHeaders:(NSArray<NSString *> *)headers rows:(NSArray<NSArray<NSString *> *> *)rows;
- (NSArray<NSNumber *> *)tableColumnWidthsForHeaders:(NSArray<NSString *> *)headers;
- (CGFloat)tableWidthForHeaders:(NSArray<NSString *> *)headers;
- (NSScrollView *)scrollableTableViewWithHeaders:(NSArray<NSString *> *)headers rows:(NSArray<NSArray<NSString *> *> *)rows;
- (NSView *)tablePanelWithTitle:(NSString *)title headers:(NSArray<NSString *> *)headers rows:(NSArray<NSArray<NSString *> *> *)rows;
- (NSArray<NSArray<NSString *> *> *)rows:(NSArray<NSArray<NSString *> *> *)rows forPage:(NSInteger)page pageSize:(NSInteger)pageSize;
- (NSInteger)safePageForPage:(NSInteger)page totalRows:(NSUInteger)totalRows pageSize:(NSInteger)pageSize;
- (NSArray<NSArray<NSString *> *> *)displayRows:(NSArray<NSArray<NSString *> *> *)rows forPage:(NSInteger)page pageSize:(NSInteger)pageSize columns:(NSUInteger)columns;
- (NSView *)paginationViewForPage:(NSInteger)page totalRows:(NSUInteger)totalRows pageSize:(NSInteger)pageSize previousAction:(SEL)previousAction nextAction:(SEL)nextAction jumpAction:(SEL)jumpAction;
- (NSView *)paginatedTablePanelWithTitle:(NSString *)title headers:(NSArray<NSString *> *)headers rows:(NSArray<NSArray<NSString *> *> *)rows page:(NSInteger)page pageSize:(NSInteger)pageSize previousAction:(SEL)previousAction nextAction:(SEL)nextAction jumpAction:(SEL)jumpAction;
- (NSView *)keyValueView:(NSArray<NSArray<NSString *> *> *)items;
- (void)showMainPage;
- (void)showAddPage;
- (void)showSettingsPage;
- (void)selectSettingsTab:(NSButton *)sender;
- (void)previousProviderStatsPage;
- (void)nextProviderStatsPage;
- (void)previousModelStatsPage;
- (void)nextModelStatsPage;
- (void)previousLogStatsPage;
- (void)nextLogStatsPage;
- (NSInteger)pageIndexFromJumpField:(NSTextField *)field;
- (void)jumpProviderStatsPage;
- (void)jumpModelStatsPage;
- (void)jumpLogStatsPage;
- (void)applySavedAppearance;
- (void)selectThemeOption:(NSButton *)sender;
- (void)selectLanguageOption:(NSButton *)sender;
- (void)chooseCodexDirectory;
- (void)saveGeneralSettings;
- (void)launchAtLoginChanged;
- (void)showRouteControlsChanged;
- (void)routeSwitchChanged;
- (void)failoverSwitchChanged;
- (NSString *)routePortFingerprintWithAddress:(NSString *)address port:(NSInteger)port;
- (void)configureRoutePortCheckForState:(NSString *)state message:(NSString *)message;
- (void)resetRoutePortCheckState;
- (BOOL)validateRouteEndpointAddress:(NSString *)address port:(NSInteger)port safePort:(NSInteger *)safePort errorMessage:(NSString **)errorMessage;
- (void)testRoutePort;
- (void)saveRouteSettings;
- (void)restoreCodexConfigFromSettings;
- (void)prepareUninstallFromSettings;
- (void)openRestoreScriptFolder;
- (void)copyDiagnostics;
- (void)resyncCodexConfiguration;
- (NSStackView *)verticalStackWithSpacing:(CGFloat)spacing;
- (void)addFullWidthView:(NSView *)view toStack:(NSStackView *)stack;
- (void)addVerticalSpacerToStack:(NSStackView *)stack;
- (NSScrollView *)scrollViewWithContent:(NSView *)content;
- (NSView *)panel;
- (NSView *)softPanel;
- (void)pinSubview:(NSView *)subview toView:(NSView *)view inset:(CGFloat)inset;
- (NSTextField *)textField:(NSString *)placeholder;
- (void)configureInputField:(NSTextField *)field;
- (void)updateInputField:(NSTextField *)field focused:(BOOL)focused;
- (NSTextField *)readonlyField:(NSString *)text;
- (NSView *)readonlySelectView:(NSString *)text;
- (void)selectAPIFormat:(id)apiFormat;
- (NSString *)selectedAPIFormat;
- (NSView *)segmentedControlWithItems:(NSArray<NSArray<NSString *> *> *)items selected:(NSString *)selected action:(SEL)action;
- (void)configureCheckButtonForState:(NSString *)state;
- (NSView *)providerPresetView;
- (void)applyProviderPreset:(NSButton *)sender;
- (NSView *)modelListView;
- (void)addModelRowWithCustomName:(NSString *)customName model:(NSString *)model;
- (void)addModelRowFromButton:(NSButton *)sender;
- (void)removeModelRow:(NSButton *)sender;
- (void)setModelRows:(NSArray<NSDictionary *> *)models;
- (NSView *)fieldGroup:(NSString *)title field:(NSView *)field;
- (void)reload;
- (NSView *)providerCard:(NSDictionary *)provider;
- (void)showMessage:(NSString *)message error:(BOOL)isError;
- (NSDictionary *)editingProvider;
- (BOOL)editingProviderModelListChangedToModels:(NSArray<NSDictionary *> *)models;
- (BOOL)confirmSaveWithChangedModelList;
- (NSString *)connectionFingerprintWithName:(NSString *)name apiKey:(NSString *)apiKey baseURL:(NSString *)baseURL apiFormat:(NSString *)apiFormat models:(NSArray<NSDictionary *> *)models tag:(NSString *)tag;
- (void)resetConnectionCheckState;
- (BOOL)isProviderFormField:(id)object;
- (void)controlTextDidChange:(NSNotification *)notification;
- (void)controlTextDidBeginEditing:(NSNotification *)notification;
- (void)controlTextDidEndEditing:(NSNotification *)notification;
- (NSArray<NSDictionary *> *)collectedModelRowsWithErrorMessage:(NSString **)errorMessage;
- (BOOL)collectFormName:(NSString **)name apiKey:(NSString **)apiKey baseURL:(NSString **)baseURL apiFormat:(NSString **)apiFormat models:(NSArray<NSDictionary *> **)models tag:(NSString **)tag fingerprint:(NSString **)fingerprint errorMessage:(NSString **)errorMessage;
- (void)testConnection;
- (void)saveProvider;
- (void)clearFormFieldsOnly;
- (void)clearForm;
- (void)copyCurrentEnv;
- (NSInteger)exportAPIKeyMode;
- (void)exportProviders;
- (void)importProviders;
- (void)setCurrentFromButton:(NSButton *)sender;
- (void)editProvider:(NSButton *)sender;
- (void)deleteProvider:(NSButton *)sender;
- (void)hideWindow;
@end
